"""Subclass of Testu_logs, which is generated by wxFormBuilder."""

import wx
import TestuLogs

# Implementing Testu_logs
class TestuLogsTestu_logs( TestuLogs.Testu_logs ):
	def __init__( self, parent ):
		TestuLogs.Testu_logs.__init__( self, parent )

	# Handlers for Testu_logs events.
	def OnClose( self, event ):
		# TODO: Implement OnClose
		pass

	def OnIdle( self, event ):
		# TODO: Implement OnIdle
		pass

	def OnVariantsA( self, event ):
		# TODO: Implement OnVariantsA
		pass

	def OnVariantsB( self, event ):
		# TODO: Implement OnVariantsB
		pass


